plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'it.unicam.cs.mpgc.rpg'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = "21.0.2"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

application {
    mainClass = 'it.unicam.cs.mpgc.rpg.m131177.Main'
}

repositories {
    mavenCentral()
}

dependencies {
    // MySQL Connector per il database
    implementation 'com.mysql:mysql-connector-j:8.3.0'
}